export { BattleNet } from './BattleNet';
export { Epic } from './Epic';
export { Github } from './Github';
export { Gog } from './Gog';
export { Heroic } from './Heroic';
export { Kofi } from './Kofi';
export { Legacy } from './Legacy';
export { Steam } from './Steam';
export { Ubisoft } from './Ubisoft';
