name: Generate and Push API Docs

on:
  push:
    branches:
      - main # Dispara sempre que o código principal for atualizado

jobs:
  build-and-push-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código principal
        uses: actions/checkout@v4

      - name: Instalar dependências de sistema do Tauri
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Dependências NPM
        run: npm install

      - name: Gerar Rustdocs
        run: npm run docs:rust
        env:
          ITAD_API_KEY: 'chave_ficticia_docs'

      - name: Gerar JSDocs (TypeDoc)
        run: npm run docs:ts

      - name: Enviar para o Repositório de Docs
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DOCS_REPO_PAT }}
        with:
          source-directory: '.api-output'
          destination-github-username: 'playlite-app'
          destination-repository-name: 'playlite-docs'
          user-email: 'alandeogoncalves@gmail.com'
          target-branch: 'main'
          target-directory: 'public/api'
          commit-message: 'chore: update API docs (auto-generated)'
